function compile(varargin)

params = {  '-I./include',...
            '-I./Bacnet_stack',...
            '-I./Bacnet_stack/include',...
            '-lWS2_32',...
            '-lIPHlpApi',...
            '-DWIN32',...
            '-DBACDL_BIP',...
            '-DMAX_TSM_TRANSACTIONS=255',...
            '-DMAX_ADDRESS_CACHE=255',...
            '-DUSE_INADDR=1',...
            '-DBACAPP_ALL',...
            '-DWRITE_PROPERTY',...
            '-DREAD_PROPERTY',...
            './source/sfun_Bacnet.c',...
            './source/bacnet_myHandler.c',...
            './source/bacnet_initHandler.c',...
            './source/bacnet_errorHandler.c',...
            './Bacnet_stack/handler/h_alarm_ack.c',...
            './Bacnet_stack/handler/h_arf.c',...
            './Bacnet_stack/handler/h_arf_a.c',...
            './Bacnet_stack/handler/h_awf.c',...
            './Bacnet_stack/handler/h_dcc.c',...
            './Bacnet_stack/handler/h_gas_a.c',...
            './Bacnet_stack/handler/h_getevent.c',...
            './Bacnet_stack/handler/h_get_alarm_sum.c',...
            './Bacnet_stack/handler/h_iam.c',...
            './Bacnet_stack/handler/h_ihave.c',...
            './Bacnet_stack/handler/h_lso.c',...
            './Bacnet_stack/handler/h_npdu.c',...
            './Bacnet_stack/handler/h_pt.c',...
            './Bacnet_stack/handler/h_pt_a.c',...
            './Bacnet_stack/handler/h_rp.c',...
            './Bacnet_stack/handler/h_rpm_a.c',...
            './Bacnet_stack/handler/h_rp_a.c',...
            './Bacnet_stack/handler/h_rr_a.c',...
            './Bacnet_stack/handler/h_ts.c',...
            './Bacnet_stack/handler/h_ucov.c',...
            './Bacnet_stack/handler/h_upt.c',...
            './Bacnet_stack/handler/h_whohas.c',...
            './Bacnet_stack/handler/h_whois.c',...
            './Bacnet_stack/handler/noserv.c',...
            './Bacnet_stack/handler/objects.c',...
            './Bacnet_stack/handler/s_ack_alarm.c',...
            './Bacnet_stack/handler/s_arfs.c',...
            './Bacnet_stack/handler/s_awfs.c',...
            './Bacnet_stack/handler/s_cevent.c',...
            './Bacnet_stack/handler/s_cov.c',...
            './Bacnet_stack/handler/s_dcc.c',...
            './Bacnet_stack/handler/s_iam.c',...
            './Bacnet_stack/handler/s_ihave.c',...
            './Bacnet_stack/handler/s_lso.c',...
            './Bacnet_stack/handler/s_ptransfer.c',...
            './Bacnet_stack/handler/s_rd.c',...
            './Bacnet_stack/handler/s_readrange.c',...
            './Bacnet_stack/handler/s_router.c',...
            './Bacnet_stack/handler/s_rp.c',...
            './Bacnet_stack/handler/s_rpm.c',...
            './Bacnet_stack/handler/s_ts.c',...
            './Bacnet_stack/handler/s_uevent.c',...
            './Bacnet_stack/handler/s_upt.c',...
            './Bacnet_stack/handler/s_whohas.c',...
            './Bacnet_stack/handler/s_whois.c',...
            './Bacnet_stack/handler/s_wp.c',...
            './Bacnet_stack/handler/s_wpm.c',...
            './Bacnet_stack/handler/txbuf.c',...
            './Bacnet_stack/src/abort.c',...
            './Bacnet_stack/src/address.c',...
            './Bacnet_stack/src/alarm_ack.c',...
            './Bacnet_stack/src/apdu.c',...
            './Bacnet_stack/src/arf.c',...
            './Bacnet_stack/src/awf.c',...
            './Bacnet_stack/src/bacaddr.c',...
            './Bacnet_stack/src/bacapp.c',...
            './Bacnet_stack/src/bacdcode.c',...
            './Bacnet_stack/src/bacdevobjpropref.c',...
            './Bacnet_stack/src/bacerror.c',...
            './Bacnet_stack/src/bacint.c',...
            './Bacnet_stack/src/bacprop.c',...
            './Bacnet_stack/src/bacpropstates.c',...
            './Bacnet_stack/src/bacreal.c',...
            './Bacnet_stack/src/bacstr.c',...
            './Bacnet_stack/src/bactext.c',...
            './Bacnet_stack/src/bactimevalue.c',...
            './Bacnet_stack/src/bigend.c',...
            './Bacnet_stack/src/bip.c',...
            './Bacnet_stack/src/bvlc.c',...
            './Bacnet_stack/src/cov.c',...
            './Bacnet_stack/src/crc.c',...
            './Bacnet_stack/src/datalink.c',...
            './Bacnet_stack/src/datetime.c',...
            './Bacnet_stack/src/dcc.c',...
            './Bacnet_stack/src/debug.c',...
            './Bacnet_stack/src/event.c',...
            './Bacnet_stack/src/fifo.c',...
            './Bacnet_stack/src/filename.c',...
            './Bacnet_stack/src/getevent.c',...
            './Bacnet_stack/src/get_alarm_sum.c',...
            './Bacnet_stack/src/iam.c',...
            './Bacnet_stack/src/ihave.c',...
            './Bacnet_stack/src/indtext.c',...
            './Bacnet_stack/src/key.c',...
            './Bacnet_stack/src/keylist.c',...
            './Bacnet_stack/src/lso.c',...
            './Bacnet_stack/src/memcopy.c',...
            './Bacnet_stack/src/mstptext.c',...
            './Bacnet_stack/src/npdu.c',...
            './Bacnet_stack/src/proplist.c',...
            './Bacnet_stack/src/ptransfer.c',...
            './Bacnet_stack/src/rd.c',...
            './Bacnet_stack/src/readrange.c',...
            './Bacnet_stack/src/reject.c',...
            './Bacnet_stack/src/ringbuf.c',...
            './Bacnet_stack/src/rp.c',...
            './Bacnet_stack/src/rpm.c',...
            './Bacnet_stack/src/sbuf.c',...
            './Bacnet_stack/src/timestamp.c',...
            './Bacnet_stack/src/timesync.c',...
            './Bacnet_stack/src/tsm.c',...
            './Bacnet_stack/src/version.c',...
            './Bacnet_stack/src/whohas.c',...
            './Bacnet_stack/src/whois.c',...
            './Bacnet_stack/src/wp.c',...
            './Bacnet_stack/src/wpm.c',...
            './Bacnet_stack/device-client.c'};

if nargin < 1
    params = [{ '-O' }, params];
else
    
    for i=1:nargin
        if strcmp(varargin{i}, 'debug') || strcmp(varargin{i}, '-g')
            params = [{ '-g', '-DDEBUG' },  params];
            continue;
        end
        
        if strcmp(varargin{i}, 'verbose') || strcmp(varargin{i}, '-v')
            params = [{ '-v' }, params];
            continue;
        end
        
        if strcmp(varargin{i}, 'optimization') || strcmp(varargin{i}, '-O')
            params = [{ '-O' }, params];
            continue;
        end
    end
end

old_dir = pwd;
cd(fileparts(which('compile.m')));


%mex('-v', '-g',...
%mex('-g','-O',...
%mex('-O',...
mex(params{:});
    


cd(old_dir);

end